### ISSUE TITLE
Expose additional configuration options from config to System Variable or TOML File parameters 

### ISSUE THREAD

**Issue by vinmestmant** [amor71/LiuAlgoTrader#117]
Please expose the following.
Right now I see some of these available in config file. would be good to have a full control over these parameter by strategy. 

1. Risk 
2. Set Portfolio value
3. Number of minutes before market close for closing positions
4. Stoploss

**Comment by amor71** [comment]
To be released in 0.0.60

**Comment by amor71** [comment]
still in process

**Comment by amor71** [comment]
@vinmestmant I've implemented 1-3, but I'm not entirely sure what you mean by `stoploss`, generally that's the role of the strategy. However, I can extend the buy/sell responses to support the recently added feature of trailing-stop -> Is that what u mean?
