### ISSUE TITLE
Project depends on TA-LIB

### ISSUE THREAD

**Issue by TheSnoozer** [amor71/LiuAlgoTrader#148]
**Describe the bug**
When I see it correctly the project has [removed](https://github.com/amor71/LiuAlgoTrader/commit/eb4d74e5f52e6aa91a70d0244d5e68a5d53efc39) the dependency to TA-LIB.
However it seems that the `MAMA` strategy is not yet replaced ([here](https://github.com/amor71/LiuAlgoTrader/blob/master/examples/mama-fama/swing_mama_fama.py#L7) and [here](https://github.com/amor71/LiuAlgoTrader/blob/master/liualgotrader/miners/daily_ohlc.py#L6)). It is also referenced as comment in [my_strategy](https://github.com/amor71/LiuAlgoTrader/blob/master/examples/my_strategy.py#L25).

**To Reproduce**
* Call `market_miner`:
* See error:
```
Traceback (most recent call last):
  File "/.venv/bin/market_miner", line 16, in <module>
    from liualgotrader.miners.daily_ohlc import DailyOHLC
  File "/.venv/lib/python3.8/site-packages/liualgotrader/miners/daily_ohlc.py", line 6, in <module>
    from talib import MAMA
ModuleNotFoundError: No module named 'talib'
```

**Expected behavior**
Either depend on talib, or find a suitable replacement for the `MAMA` strategy.

**Desktop (please complete the following information):**
```
$ python --version
Python 3.8.0
$ pip freeze | grep liu
liualgotrader==0.0.82
```

**Comment by amor71** [comment]
@TheSnoozer thank you for your comment. Personally, I do use TALIB for my strategies that I write on top of the liu-framework. However, various users mentioned issues w/ compiling the library on Windows, which is why I took out the dependency. I will remove it from the market_miner, and leave it in the samples directory with a clear indication of the dependency.

**Comment by amor71** [comment]
To-be-released in 0.0.85

**Comment by TheSnoozer** [comment]
Hi,
yeah no worries. I have noticed the dependency in the strategies (e.g. [this one](https://github.com/amor71/trading_strategies/blob/1c2c123811f7c55ad894cf4d02cee38c76f43f98/momentum_long_v6.py#L18)) so I wasn't sure if this is now a required dependency for this project or not :-).
I have installed talib locally (on linux so I had no issue in installing) so feel free to fix whenever.

**Comment by amor71** [comment]
merged your PR it's now currently in `master` together with a collection of changes that I plan to release as `0.0.85` by end of the week. Thank you for your help, I added you as a contributor, and hope to see more stuff from you. Let me know if you have any issues/suggestions/comments or flames. Happy New Year!
