### ISSUE TITLE
In what areas would you suggest to start off my contributions?

### ISSUE THREAD

**Issue by riven314** [amor71/LiuAlgoTrader#212]
This project looks super impressive! I rarely see an end-to-end algo trading framework like this get open-sourced. In addition, the tools that you use (e.g. streamlit) is pretty up-to-update from Data Science perspective, also it has a solid automation flow to facilitate the dev pipeline. The whole framework shows a nice mix of data science, quant and software engineering.   

I would love to contribute to this project. I particularly like the part you have a pretty cool interface to do analysis such as backtesting. However my algo trading experience is very limited. Is there any way I could help contribute to this project? Look forward to your reply!

Alex

**Comment by amor71** [comment]
Thank you Alex, and looking forward to collaborating. Tell me a bit more on
your experience & interests - are you on the data-science side?
multi-processing? all-around developer?

**Comment by riven314** [comment]
I come from statistics background, so previously work mainly evolved around data science. But due to current job nature, my interest is gradually expanding towards software engineering side. 
About this project, I am particularly interested in your data extraction pipeline, backtesting framework and the interfaces for analysis/ reporting.

**Comment by amor71** [comment]
I have few ideas, I think it will be easier to switch to the conversation
to https://gitter.im/LiuAlgoTrader/community (you can direct message me)
