### ISSUE TITLE
proof read documentation

### ISSUE THREAD

**Issue by amor71** [amor71/LiuAlgoTrader#219]
**Is your feature request related to a problem? Please describe.**
review documentation, make sure it's current, accurate, and uses correct English

**Comment by LadySqrrl** [comment]
I'd be happy to proofread the documentation if it's still needed.

**Comment by amor71** [comment]
@LadySqrrl  Thank you for willing to collaborate. @riven314 has already started with this task, but we can discuss your assistance on other tasks that may be helpful for first-time users.  You can directly chat w/ me [here](https://gitter.im/LiuAlgoTrader/community) and we'll figure this out?
