### ISSUE TITLE
Unable to start LiuAlgoTrader in Firefox

### ISSUE THREAD

**Issue by ksilo** [amor71/LiuAlgoTrader#239]
**Describe the bug**
Unable to start LiuAlgoTrader in Firefox on Linux Debian 

**To Reproduce**
Installation tutorial was followed exactly and all prerequisites were met

**Screenshots**
![Screenshot from 2021-09-24 07-35-13](https://user-images.githubusercontent.com/91175005/134619626-026d0052-1425-4f5f-a6bc-ee3cc95057e5.png)

**Desktop (please complete the following information):**
 - Linux Debian 10
 - Firefox ESR
 - 78.14.0esr (64-bit)

**Comment by amor71** [comment]
@ksilo It looks like DB connection failed:
1. Is your Docker engine working, and running the PostgreSQL?
2. Are you able to connect to the DB?

**Comment by ksilo** [comment]
@amor71 everything seems up and running

![Screenshot from 2021-09-24 14-08-38](https://user-images.githubusercontent.com/91175005/134665254-76609f8f-7a7d-46c9-819b-15ae03be0ea0.png)
g

**Comment by amor71** [comment]
Are you able to connect to local DB, using the port in your DSN environment variable? PG has a command-line tool called ‘psql’ : can u pls confirm you can use it to access the DB? If so i will replicate your setup and test. Lmk.

**Comment by ksilo** [comment]
Yes, I can connect using \psql -h localhost -p 5400 -U liu

**Comment by amor71** [comment]
Pls see the error - it is trying to connect to a different port - i think issue is in your DSN (see the .sh)

**Comment by amor71** [comment]
@ksilo  The error shows:

![image](https://user-images.githubusercontent.com/48661380/134752600-8b2aa7bf-7376-459e-bf29-85dbfdc27e29.png)

The installation wizard should have created a file `env_vars.sh` and you're supposed to run it before running `streamlit`. The file should be something like this:

`export DSN=postgresql://liu:liu@localhost:5400/liu`

That should direct the DB session creation to port 5400 and now 5432 -> Are you 100% sure you executed the script prior? Does it look like the above?

Can you take a screenshot of the DSN prior to running `stteamlit`

**Comment by ksilo** [comment]
@amor71 I think what's happening is: installation wizard can't access 
https://raw.githubusercontent.com/amor71/LiuAlgoTrader/master/examples/quickstart/ 

probablly that's why env_vars.sh scrip isn't created

**Comment by amor71** [comment]
@ksilo The liu application creates the file, I'm not sure what you mean by can't access it?

```
            with open(f"{samples_location}env_vars.sh", "w") as f:
                f.write(
                    f"export DSN=postgresql://{user}:{passwd}@localhost:5400/{db}\n"
                )
```

Was the file not created for you, in the subfolder? Can you please confirm that and I'll look further?

**Comment by ksilo** [comment]
sample files were not created in the sub folder, files = ["tradeplan.toml", "vwap_short.py", "momentum_long_simplified.py"],  env_vars.sh scrip was not created also

i check the liu.py source code and found the link is not working in def setup_samples (400: Invalid request)

**Comment by amor71** [comment]
These files are no supposed to be created anymore, that should not be an issues but the env script should be created (its not downloaded..). I tested it couple of days ago, I will retest and post on this thread.

**Comment by ksilo** [comment]
nothing, I don't have liu_samples folder, just liu_dat

![Screenshot from 2021-09-25 17-00-29](https://user-images.githubusercontent.com/91175005/134774163-03cdf797-dd9d-4d13-99ae-c7fd67746fc1.png)
a

**Comment by amor71** [comment]
@ksilo I just restarted from scratch, and I do see the files. Can u please try to re-run the `liu quickstart` and confirm you selected to create the samples. Thank you for checking.

![image](https://user-images.githubusercontent.com/48661380/134778344-01b41efe-63c2-489f-b1a7-60c05019ddd3.png)


![image](https://user-images.githubusercontent.com/48661380/134778303-b23ff61b-ef0c-4056-b615-a158de22ea0c.png)

**Comment by ksilo** [comment]
nope, setting up samples step not start
![Screenshot from 2021-09-25 19-28-24](https://user-images.githubusercontent.com/91175005/134778883-46e03c6e-5729-4b7f-92f0-18e0b81dea1a.png)
![Screenshot from 2021-09-25 19-31-58](https://user-images.githubusercontent.com/91175005/134778886-e880faf0-bedd-45b3-b756-698ada69aab7.png)
![Screenshot from 2021-09-25 19-32-16](https://user-images.githubusercontent.com/91175005/134778890-4e8f8578-52f5-46f2-9bf5-97a57716ff34.png)

**Comment by amor71** [comment]
So the entire step did you take place, even when you entered Y ? 

So strange

**Comment by ksilo** [comment]
yep, as you see, I don't get prompt for selecting location for sample files

**Comment by amor71** [comment]
@ksilo Thanks for sharing the full details. I found the issue and pushed a fix. Version 0.3.27 has just been published. 

The issue was that you entered "Y" instead of pressing the enter key... 

This line failed:
`samples = not len(i) or i.lower in ("y", "yes")`
it should be:
`samples = not len(i) or i.lower() in ("y", "yes")`

Can you please pull the latest (0.3.27) and confirm the fix and close the issue?

Thanks much for noticing, well done!

**Comment by ksilo** [comment]
yes! everything is working now!
