### ISSUE TITLE
ModuleNotFoundError: No module named 'liualgotrader.trading.tradier' when running backtester

### ISSUE THREAD

**Issue by AleFestante** [amor71/LiuAlgoTrader#331]
Hi! I think I might have found a bug (probably fell between versions)
`liualgotrader.backtester ` tries to  `liualgotrader.trading.tradier import TradierTrader` but that is currently missing from the package.

**To Reproduce**
1. install liualgotrader
2. download sample data

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/60609350/164943016-93a2e0b6-0a91-410c-9e46-2d8e683f80b4.png)

**Comment by amor71** [comment]
@AleFestante thank you for bringing it to my attention and my apologies for the slow response. I will handle this and keep you posted. Sorry about that.

**Comment by amor71** [comment]
@AleFestante I am unable to re-produce the issue. Can you please explain how you installed the platform? Did you use `pip` or did you clone from GitHub? BTW, to run `backtester` you need to create a .toml file, but firstly I'd like to reproduce the issue.

**Comment by AleFestante** [comment]
> @AleFestante I am unable to re-produce the issue. Can you please explain how you installed the platform? Did you use `pip` or did you clone from GitHub? BTW, to run `backtester` you need to create a .toml file, but firstly I'd like to reproduce the issue.

Sorry about the slow response. 
I used pip, but after the error I downgraded to the previous version and it ran fine.
I will try to upgrade again to the current version and see what happens.

**Comment by amor71** [comment]
@angrycarrots I tried both 3.9 and 3.10 (which is the version I'm using), and I can't reproduce the issue... happy if you can share additional details

**Comment by adenhertog** [comment]
Hi @amor71 thanks for this platform, I'm really keen to test it out.

I've hit the same issue as the OP. The steps I took were:

(Platform Mac 11.6.5, Python 3.9, pip3 22.1.1, using venv: no)

- pip3 install liualgotrader
- liu quickstart
- portfolio create 10000 1000 US_EQUITIES

![image](https://user-images.githubusercontent.com/6031613/170848605-5870582d-1750-4f14-b44d-49c34fe56381.png)

Running v0.4.20:

![image](https://user-images.githubusercontent.com/6031613/170848624-c64e2e5f-17df-4120-b17a-f39062c65b77.png)

When I look at the source of the error (`trader_factory.py`), it doesn't have a `tradier.py` definition:
 
![image](https://user-images.githubusercontent.com/6031613/170848741-844733da-eb3d-434f-927a-15787a7150fd.png)

I've looked in the master branch at this folder, and I can't see that file either:

![image](https://user-images.githubusercontent.com/6031613/170848758-15e00918-1612-4053-8438-895792c65d44.png)

On a side note I've set `LIU_BROKER=alpaca`, which I thought would bypass the factory building a `TradierTrader`, but I haven't looked into that much:

`trader_factory.py`

![image](https://user-images.githubusercontent.com/6031613/170848859-4ad73e6f-268d-45df-9da3-126559a14a82.png)

**Comment by adenhertog** [comment]
quick update - I removed the `from liualgotrader.trading.tradier import TradierTrader` line from `trader_factory.py` and it worked for me

**Comment by amor71** [comment]
@adenhertog @angrycarrots @AleFestante I managed to reproduce and found the issue. I will be releasing a fixed version together with several upgrades in a couple of days. I appreciate your patience.

**Comment by amor71** [comment]
resolved. thanks.
