### ISSUE TITLE
`python setup.py install` fails under python 3.9.5

### ISSUE THREAD

**Issue by TheSnoozer** [amor71/LiuAlgoTrader#342]
**Describe the bug**
Hello,
I'm currently having trouble to install the project with `python setup.py install`.
Something along the lines of
```
rm -rf .venv
python3.9 -m virtualenv .venv
source .venv/bin/activate
python -m pip install -U pip setuptools
python setup.py install
```
fails with:
a) `error: protobuf 4.21.2 is installed but protobuf<4.0.0dev,>=3.12.0 is required by {'google-api-core'}`
b) `error: grpcio 1.44.0 is installed but grpcio>=1.47.0 is required by {'grpcio-status'}`
depending on what commit is checked out.

**To Reproduce**
Either:
git checkout upstream/pyup/scheduled-update-2022-06-27
or
git checkout v0.0.82
or 
git checkout d00ab72f6a41c487c177b2a11b68ab4623301439
or
git checkout 9ebd4564ddef13aff718d95d18596b5e3954cef1
and run the `python setup.py install` as mentioned above.

Anything that I'm missing here? Thanks for the help!

**Desktop (please complete the following information):**
```
$ python --version
Python 3.9.5
```
```
$ cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by amor71** [comment]
@TheSnoozer Thank you for pointing this out, I'll get back to you shortly.

**Comment by amor71** [comment]
@TheSnoozer I pushed to master reduced dependencies. Could you please test and LMK if the issue is resolved? If so, I will release it.

**Comment by TheSnoozer** [comment]
Hi,
thanks for the update after removing
```
mnqueues==0.0.38
```
from ```liualgotrader/requirements/release.txt``` a ``python setup.py install`` works.
I have created https://github.com/amor71/LiuAlgoTrader/pull/343 and thus will close this ticket.


Thanks for your quick support!
