### ISSUE TITLE
UnboundLocalError on quickstart

### ISSUE THREAD

**Issue by savex83** [amor71/LiuAlgoTrader#381]
**Describe the bug**
After compiling the "liu quickstart" setup, you get an "UnboundLocalError: local variable 'user_name' referenced before assignment" error.

**To Reproduce**
1. Follow the [QuickStart](https://liualgotrader.readthedocs.io/en/latest/Quickstart.html) steps
2. set all the envs
3. See the error after pressing [ENTER] when "Ready to go?? Press [ENTER] to start the installation.." 

**Expected behavior**
Complete the quickstart process

**Screenshots**
![image](https://user-images.githubusercontent.com/6159502/209587015-4d406b44-931b-4077-9a07-05f77f79bb4d.png)

**Desktop (please complete the following information):**
 - OS: Apple MacOS Ventura 13.0.1 (22A400)
 - Python 3.10.6

**Additional context**
DSN it's like driver://username:password@host:port/database

**Comment by amor71** [comment]
@savex83 thank you for reporting, are you still having this issue w/ the latest version?

**Comment by jhuynh08** [comment]
@amor71 I'm seeing this exact same issue as well on the the latest version when I ran quickstart with the DSN variable set.

export DSN="postgres://redacted-username][redacted-pw]@[redacted-server]:5432/tradedb"

<img width="996" alt="image" src="https://user-images.githubusercontent.com/57417573/214715881-297a9aaf-e7b7-4eaa-8b0c-233e19ab6550.png">

**Comment by jhuynh08** [comment]
Seems to only happen if I want to view and download the samples. If I just select no, it finishes the installation.

**Comment by amor71** [comment]
@jhuynh08 in `Step #2,` the quickstart requests you to enter a user-name. Which seems to be missing here. Can you confirm you entered a username? Would you be so kind as to send a screenshot of `Step #2` an I'll handle it quickly? Thanks!
