### ISSUE TITLE
OSError: Multiple exceptions: [Errno 61] Connect call failed ('::1', 5432, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 5432)

### ISSUE THREAD

**Issue by wmelton** [amor71/LiuAlgoTrader#386]
**Describe the bug**
Clean install on MacOS running Docker Desktop 4.15. For reasons I'm unable to figure out, streamlit, portfolio create, etc. are unable to connect to PostGres.

I've verified Docker image started, PostGres is running, and no errors are present in logs, but Liu will not successfully connect.

![image](https://user-images.githubusercontent.com/1544125/213842170-b35fa681-5106-4084-a21a-aeea1c60a10b.png)

**Desktop (please complete the following information):**
 - MacOS Monterey
- 12.2.1

**Comment by amor71** [comment]
@wmelton is that log from your docker?!

**Comment by wmelton** [comment]
@amor71 no, that's from your package attempting to connect to the postgres instance launched via docker compose at run time.

**Comment by amor71** [comment]
@wmelton after you run `liu quickstart` there are details at the end. among it is to run environment variables, which set the port to 5400, your example is looking for port 5431 which makes me think we didn't follow all steps, and hence you can't connect to the Postgres running on the docker.

**Comment by wmelton** [comment]
@amor71 where?

```bash
+--------------------+
| setting up samples |
+--------------------+
Downloading https://raw.github.com/amor71/LiuAlgoTrader/master/examples/quickstart/tradeplan.toml to /Users/user/Documents/Dev/alpaca/liu_samples/...
Downloading https://raw.github.com/amor71/LiuAlgoTrader/master/examples/quickstart/vwap_short.py to /Users/user/Documents/Dev/alpaca/liu_samples/...
Downloading https://raw.github.com/amor71/LiuAlgoTrader/master/examples/quickstart/momentum_long_simplified.py to /Users/user/Documents/Dev/alpaca/liu_samples/...

creating environment variables script
setup completed successfully.


+---------------+
| what's next?  |
+---------------+

Congratulations, Liu Algo Trader is ready to go!
From here, you can either run the back-testing UI, or read the docs.
The full documentation is available here: `https://liualgotrader.rtfd.io/`.

The restored database includes data for the first week and half of Oct 2020.
You may now run a back-testing sessions for these days, as well as 
analyze an existing trading session.

To experience Liu Algo Trading for the first time:
1. change your working directory to the sample directory /Users/wesmelton/Documents/Dev/alpaca/liu_samples ('cd /Users/wesmelton/Documents/Dev/alpaca/liu_samples'),
2. run the env-vars script ('source env_vars.sh'),
3.`streamlit run https://raw.github.com/amor71/LiuAlgoTrader/master/analysis/backtester_ui.py`
4. On the app selection select the 'analyzer` app
5. copy and paste the batch-id '2398380c-5146-4b58-843a-a50c458c8071' and press <enter>

Thank you for choosing Liu Algo Trading Framework.
```

**Comment by wmelton** [comment]
@amor71 so it looks like the env_vars.sh script does set it up, however, I'm pretty sure the `liu_samples` folder only gets created if you tell the quickstart prompt to include samples. Might be a worthy update to create the `env_var.sh` file in the root of the project. 

After running `env_vars.sh` the issue is resolved. Thanks!
