### ISSUE TITLE
Backtesting on a market closed day

### ISSUE THREAD

**Issue by aivisol** [amor71/LiuAlgoTrader#404]
**Describe the bug**
Running backtesting on day when markets are closed, throws following error:

```
[backtest()][49032]2023-10-08 13:18:41.303132:backtest() - exception of type IndexError with args ('list index out of range',)
 ...
  File "/opt/homebrew/lib/python3.11/site-packages/liualgotrader/trading/alpaca.py", line 58, in __init__
    calendar = self.alpaca_rest_client.get_calendar(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
```

Most likely caused by this: https://github.com/amor71/LiuAlgoTrader/blob/3df70067cf7a419115259956c64b50c5c07931db/liualgotrader/trading/alpaca.py#L58

Suggesting to change it to:

```
        try:
            calendar = self.alpaca_rest_client.get_calendar(
                start=now.strftime("%Y-%m-%d"), end=now.strftime("%Y-%m-%d")
            )[0]
        except IndexError:
            self.market_open = self.market_close = None
            super().__init__(qm)
            return
```

Let me know if this makes sense, I can send a PR.

thanks.

**Comment by oaimtiaz** [comment]
I had this issue too. Not sure if a fix is planned for this, so for a quick workaround, you can directly modify the executable script. Here's some steps on how to do it:
1. Find where the script is installed
```py
import liualgotrader.trading.alpaca

print(liualgotrader.trading.alpaca.__file__)
```
2. Now, open this file in your editor and replace with @aivisol's suggested code above. Until a fix is implemented/merged in, you should be able to run the backtester!
